=== nerilex/crypto-testvectors-xml/xml/schema/hash-function_kat.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://testvectors.cryptolib.org/xml-schema/v0.1/hash-function_kat"
xmlns:kat="https://testvectors.cryptolib.org/xml-schema/v0.1/hash-function_kat"
xmlns:types="https://testvectors.cryptolib.org/xml-schema/v0.1/basic-types"
elementFormDefault="qualified">

<xs:import 
  namespace="https://testvectors.cryptolib.org/xml-schema/v0.1/basic-types"
  schemaLocation="basic-types.xsd"
/>


  <xs:complexType name="katVector">
    <xs:sequence>
      <xs:element name="comment" type="xs:string" minOccurs="0"/>
      <xs:element name="algorithm" type="xs:string" minOccurs="0"/>
      <xs:element name="message" type="types:hexBitVector"/>
      <xs:element name="digest" type="types:hexBitVector"/>
    </xs:sequence>
    <xs:attribute name="operation" type="xs:string"/>
    <xs:attribute name="index" type="xs:decimal"/>
  </xs:complexType>


<xs:element name="testFile">
<xs:complexType>
    <xs:sequence>
    
<xs:element name="header">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="convertDate" type="xs:dateTime" minOccurs="0" />
      <xs:element name="originalFilename" type="xs:string" minOccurs="0" />
      <xs:element name="originalSha256" type="xs:hexBinary" minOccurs="0" />
      <xs:element name="originalSha512" type="xs:hexBinary" minOccurs="0" />
      <xs:element name="algorithm" type="xs:string" minOccurs="0"/>
      <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="body">
<xs:complexType>
  <xs:choice>
    <xs:element name="katVector" type="kat:katVector" maxOccurs="unbounded"/>
  </xs:choice>
</xs:complexType>
</xs:element>
  </xs:sequence>
</xs:complexType>
  
</xs:element>

</xs:schema>

=== nerilex/crypto-testvectors-xml/xml/testvectors/sha2/shavs/shabytetestvectors/SHA512_224ShortMsg.xml
<?xml version="1.0"?>
<testFile
  xmlns="https://testvectors.cryptolib.org/xml-schema/v0.1/hash-function_kat" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://testvectors.cryptolib.org/xml-schema/v0.1/hash-function_kat
                      ../../../../../xml/schema/hash-function_kat.xsd">
<header>
  <convertDate>2017-08-08T10:59:07+02:00</convertDate>
  <originalFilename>SHA512_224ShortMsg.rsp</originalFilename>
  <originalSha256>9b11fb25ff08d8c708e098a22d013c5d38c068d1e398eb573d2055c053bffe75</originalSha256>
  <originalSha512>50aad46bdfc75af8f6168294c28d54d822b00c497724a19518b71355e1d8547c5a5ab4266bf84dcec443f8bdd6127d76a61f3be9c4939dd5eff9383cb62eb667</originalSha512>
  <comment>CAVS 21.1</comment>
  <comment>"SHA-512/224 ShortMsg" information for "sha_values"</comment>
  <comment>SHA-512/224 tests are configured for BYTE oriented implementations</comment>
  <comment>Generated on Mon Jul 10 14:34:13 2017</comment>
</header>

<body>

  <katVector index="0">
    <message bitLength="0" bitOrder="mostSignificantFirst" >
      00
    </message>
    <digest>6ed0dd02806fa89e25de060c19d3ac86cabb87d6a0ddd05c333b84f4</digest>
  </katVector>

  <katVector index="1">
    <message bitLength="8" bitOrder="mostSignificantFirst" >
      cf
    </message>
    <digest>4199239e87d47b6feda016802bf367fb6e8b5655eff6225cb2668f4a</digest>
  </katVector>

  <katVector index="2">
    <message bitLength="16" bitOrder="mostSignificantFirst" >
      ca2d
    </message>
    <digest>392b99b593b85e147f031986c2a9edfdb4ffd9f24c77c452d339c9fc</digest>
  </katVector>

  <katVector index="3">
    <message bitLength="24" bitOrder="mostSignificantFirst" >
      497604
    </message>
    <digest>a9c345d58a959af20a42c84e28523ba47e3bf8fad8e8c3f32b7a72ae</digest>
  </katVector>

  <katVector index="4">
    <message bitLength="32" bitOrder="mostSignificantFirst" >
      c2eb0c88
    </message>
    <digest>c5b97f1e46d91c3940be8cfef1e49baa77b475db943e49f00cddbe72</digest>
  </katVector>

  <katVector index="5">
    <message bitLength="40" bitOrder="mostSignificantFirst" >
      d28bc2aa3f
    </message>
    <digest>e79de552120a87585e7313e24ecd74139a3be9ba2812936c4b33ca23</digest>
  </katVector>

  <katVector index="6">
    <message bitLength="48" bitOrder="mostSignificantFirst" >
      b4142ca79f6d
    </message>
    <digest>2a0ed8eb0e18bc189f5c836dc6a5825baa6f7286fa5b9689b641bb3b</digest>
  </katVector>

  <katVector index="7">
    <message bitLength="56" bitOrder="mostSignificantFirst" >
      8daedf3c420c8c
    </message>
    <digest>4edac91a8eba35a1431ef4d49705db12da382a786d15636774cbd708</digest>
  </katVector>

  <katVector index="8">
    <message bitLength="64" bitOrder="mostSignificantFirst" >
      6963446913771410
    </message>
    <digest>21f6c373637e6a5e89d6e88811110c5c3fa12e497144912914c546e1</digest>
  </katVector>

  <katVector index="9">
    <message bitLength="72" bitOrder="mostSignificantFirst" >
      6f316ab2b40f096819
    </message>
    <digest>5899542e9a78d1403929c4346993e213b83c32f91274bddbc63e4192</digest>
  </katVector>

  <katVector index="10">
    <message bitLength="80" bitOrder="mostSignificantFirst" >
      5819a77fa1a8f9c35d17
    </message>
    <digest>2e944a5c534b80922f6c21e97277b4a01a4a0fa652d6d40b37fb0fc9</digest>
  </katVector>

  <katVector index="11">
    <message bitLength="88" bitOrder="mostSignificantFirst" >
      3c7e038401fa74c6c06e41
    </message>
    <digest>a74af68819afe81bcdaceba64201c0d41f843e4b08e4002a375be761</digest>
  </katVector>

  <katVector index="12">
    <message bitLength="96" bitOrder="mostSignificantFirst" >
      e243b9f901855447fa2af302
    </message>
    <digest>330c77ed20dc93cabf0df3442c620c9df5c7a02d7c79fc1d2ff7ff94</digest>
  </katVector>

  <katVector index="13">
    <message bitLength="104" bitOrder="mostSignificantFirst" >
      c5f942edc46407c6019cd926a0
    </message>
    <digest>e180a0d83683cb7e79d812ab5d4288399c78895c6a918e99a2839155</digest>
  </katVector>

  <katVector index="14">
    <message bitLength="112" bitOrder="mostSignificantFirst" >
      e57d4c478ad6a64b8bf3352e75b6
    </message>
    <digest>18b3e8f5a1fb603c67060c12a736e57c5ccc0b89fc62c90b02dd926b</digest>
  </katVector>

  <katVector index="15">
    <message bitLength="120" bitOrder="mostSignificantFirst" >
      32d049928a583b5b954785805d8b26
    </message>
    <digest>18f87e8e6b54ec4336442f76eda0b32dcb64d463c0be69e348f86c34</digest>
  </katVector>

  <katVector index="16">
    <message bitLength="128" bitOrder="mostSignificantFirst" >
      3b2542cb3fa560dd0d796d59ee151fee
    </message>
    <digest>dc4ab34db241b3fc2055c54f70a8fd304523d8c4202852f5f077644f</digest>
  </katVector>

  <katVector index="17">
    <message bitLength="136" bitOrder="mostSignificantFirst" >
      ecbe367959a91b15eb08048b33752ef76d
    </message>
    <digest>b76eaa7dde45ed50c07b5bafafbfdcc0959c1a64eca7adc391aba245</digest>
  </katVector>

  <katVector index="18">
    <message bitLength="144" bitOrder="mostSignificantFirst" >
      40bd7d47b636c2a749a247fdda75807c238b
    </message>
    <digest>087ed68f1db90ffb2fb4ff7dc4b17fe08100b64383850378ef543339</digest>
  </katVector>

  <katVector index="19">
    <message bitLength="152" bitOrder="mostSignificantFirst" >
      331c8939ef685ae0efcd4030378a8b0ab720c7
    </message>
    <digest>97874d56296a28f8df280448f76a9e806605da257a6083598f232e4d</digest>
  </katVector>

  <katVector index="20">
    <message bitLength="160" bitOrder="mostSignificantFirst" >
      26634d1eb3cc2793830c97f49674bda74743eb8f
    </message>
    <digest>8294b112588dfb9c553ac88fbd8441722cec6a1d435311fe72e0110c</digest>
  </katVector>

  <katVector index="21">
    <message bitLength="168" bitOrder="mostSignificantFirst" >
      62ed23ab88c30fe1350f702f3b6d45253a0fc6aec1
    </message>
    <digest>309db70638771e2eec309abfda219e5f13bac5fa9d5e84e727764bca</digest>
  </katVector>

  <katVector index="22">
    <message bitLength="176" bitOrder="mostSignificantFirst" >
      827dbbe36fb2663c95eaf81c7ce441dca66405050ad8
    </message>
    <digest>39e786a93dc90e96471e466950a5a0f7f142ca69c1251b932e8bbf45</digest>
  </katVector>

  <katVector index="23">
    <message bitLength="184" bitOrder="mostSignificantFirst" >
      a2ada61a95cf8fb6f93cbd0aa67b70e286dc853afa51f8
    </message>
    <digest>e821247c7bc7ac8ef07fb31ac25fb48a3fbc50fde399a3cb5889545f</digest>
  </katVector>

  <katVector index="24">
    <message bitLength="192" bitOrder="mostSignificantFirst" >
      5633ee7b8870002c01a3c6f68f7812f13adfe0bf6fa794bf
    </message>
    <digest>c34b467858b65202fd8c73ffac67cd8ee55118d12beb2b110b63ae43</digest>
  </katVector>

  <katVector index="25">
    <message bitLength="200" bitOrder="mostSignificantFirst" >
      da1dd1ebea3cc9474cf255dc23e35695026e86d6093abab251
    </message>
    <digest>e650802f29ad20b900148cf3e9361399e6207d455257fbae3efee50c</digest>
  </katVector>

  <katVector index="26">
    <message bitLength="208" bitOrder="mostSignificantFirst" >
      8f71c9344ce6a535d104803d22119f57b5f9477e253817a52afa
    </message>
    <digest>6b3a288bd84137cd7600ccf2d2ab9b797d0e87a18ccb468183396235</digest>
  </katVector>

  <katVector index="27">
    <message bitLength="216" bitOrder="mostSignificantFirst" >
      d668a21780594024db025dcb373ef3639bcd5743145527e24da67d
    </message>
    <digest>2b93446d3aa2f1f9ea858e47806cc472f40e33085b7c7a6522cf6548</digest>
  </katVector>

  <katVector index="28">
    <message bitLength="224" bitOrder="mostSignificantFirst" >
      03f8cf98035eac158ff18fd93b44cdb621597255d7c3d97a9e087989
    </message>
    <digest>e1fc5f508deed8bf74883b6fdef8c3e0c86306e7f1d6300cce4d36dc</digest>
  </katVector>

  <katVector index="29">
    <message bitLength="232" bitOrder="mostSignificantFirst" >
      2a1f57998360e9216f5040e8f75f5bffba4368eeedede54aa0bb058a43
    </message>
    <digest>bdc91e679fc2f4e40af13f03eca3f61a7ba33ac2c613d948ed7fc0bc</digest>
  </katVector>

  <katVector index="30">
    <message bitLength="240" bitOrder="mostSignificantFirst" >
      cd5fee5fde5e9aa2884b4f4882cfa7d5571f8fd572c5f9bf77a3d21fda35
    </message>
    <digest>72b43417b071f4811833027731b0ca28549c0357530fe258ca00533e</digest>
  </katVector>

  <katVector index="31">
    <message bitLength="248" bitOrder="mostSignificantFirst" >
      a9a73038a28e40feb374819df3a26db846fda284de7e88db01e2348c0ca38c
    </message>
    <digest>a5baddceed5b58614c95b8a621d58cd4b12559bd34795ef5be9cd603</digest>
  </katVector>

  <katVector index="32">
    <message bitLength="256" bitOrder="mostSignificantFirst" >
      be4850f5be6cb68cdba5948e3b94dbbce82989aa75b97073e55139aac849a894
      
    </message>
    <digest>c11eedaadc5249cefafc5a9fadf39e812db700bd2767b8de1cdd6099</digest>
  </katVector>

  <katVector index="33">
    <message bitLength="264" bitOrder="mostSignificantFirst" >
      ced78bf0734a527f5c07ef6c8adf80ae252b8cff100d393ec1f8c01150721fce
      cd
    </message>
    <digest>d4237aa1956d37a6dcab7b07269f18228f7e3156c3555cf4d3d68c1a</digest>
  </katVector>

  <katVector index="34">
    <message bitLength="272" bitOrder="mostSignificantFirst" >
      e400bc8994cff23eae189df3b1e7e440a6b5b1786197128105b5dfe2c6fe9d1e
      f31a
    </message>
    <digest>45351adffefcfb5e39085461f8bff5f5652a5aa5a0401f04d4f56452</digest>
  </katVector>

  <katVector index="35">
    <message bitLength="280" bitOrder="mostSignificantFirst" >
      f15284a11c61e129ea0606bd6531f2f1213776e01e253d1def530bed1c3c42b3
      c68caa
    </message>
    <digest>fa425bc732d6033566c073560b2c5fe322aa4fa22aaa3ec51154ffd8</digest>
  </katVector>

  <katVector index="36">
    <message bitLength="288" bitOrder="mostSignificantFirst" >
      d858eed942fe926b52bada623fb8d0f18458e4163332e1c18c581f38cedafbba
      4d908462
    </message>
    <digest>b2b308db948d7169c8eebb4d7a19be96d5c4b5849593ec587d3865e6</digest>
  </katVector>

  <katVector index="37">
    <message bitLength="296" bitOrder="mostSignificantFirst" >
